# https://hexo.io/docs/configuration.html
title: danilo neves cruz
subtitle: game developer
description: i'm a computer scientist and i've been developing games and interactive digital content for more than 10 years. this is my portfolio.
author: danilo neves cruz
url: https://cruzdanilo.com
permalink: :title/
theme: cruzdanilo
per_page: 0
post_asset_folder: true
pretty_urls:
  trailing_index: false
cover:
  width: 54 # 27
  height: 82 # 41
manifest:
  path: manifest.json
  data:
    name: cruzdanilo
    short_name: cruzdanilo
    start_url: /
    orientation: landscape
    theme_color: black
    background_color: black
    display: standalone
