# https://hexo.io/docs/configuration.html
title: danilo neves cruz
subtitle: game developer
description: i'm a computer scientist and i've been developing games and interactive digital content for more than 10 years. this is my portfolio.
author: danilo neves cruz
language: en
url: https://cruzdanilo.com
permalink: :title/
theme: cruzdanilo
post_asset_folder: true
per_page: 0

## https://github.com/hexojs/hexo-filter-responsive-images
responsive_images:
  pattern: '*/*.+(png|jpg|jpeg)'
  sizes:
    cover:
      width: 54 # 27
      height: 82 # 41
